import type { ChapterQuiz } from "@/content/quiz-types";

export const quiz: ChapterQuiz = {
  questions: [
    {
      prompt: {
        pl: "Czym jest embedding tekstu?",
        en: "What is a text embedding?",
      },
      options: [
        {
          text: {
            pl: "Wektor liczb reprezentujący znaczenie tekstu, gdzie podobne sensy leżą blisko siebie",
            en: "A vector of numbers representing the meaning of text, where similar meanings sit close together",
          },
        },
        {
          text: {
            pl: "Skrót tekstu wygenerowany przez model językowy",
            en: "A summary of the text generated by a language model",
          },
        },
        {
          text: {
            pl: "Lista słów kluczowych wyciągniętych z dokumentu",
            en: "A list of keywords extracted from the document",
          },
        },
        {
          text: {
            pl: "Skompresowana wersja pliku tekstowego",
            en: "A compressed version of the text file",
          },
        },
      ],
      answer: 0,
      explanation: {
        pl: "Embedding to wektor zmiennoprzecinkowy. Teksty o podobnym znaczeniu dają wektory blisko siebie, co pozwala porównywać sens, a nie litery.",
        en: "An embedding is a floating-point vector. Texts with similar meaning produce vectors close together, which lets you compare meaning rather than letters.",
      },
    },
    {
      prompt: {
        pl: "Której metody Embeddera użyjesz dla pojedynczego pytania wyszukiwania?",
        en: "Which Embedder method do you use for a single search query?",
      },
      options: [
        { text: { pl: "embed_query()", en: "embed_query()" } },
        { text: { pl: "embed_documents()", en: "embed_documents()" } },
        { text: { pl: "count_tokens()", en: "count_tokens()" } },
        { text: { pl: "max_input_tokens()", en: "max_input_tokens()" } },
      ],
      answer: 0,
      explanation: {
        pl: "embed_query() jest przeznaczona dla zapytań, a embed_documents() dla wsadu treści, którą indeksujesz. Niektóre modele optymalizują oba przypadki inaczej.",
        en: "embed_query() is for queries, while embed_documents() is for the batch of content you index. Some models optimize the two cases differently.",
      },
    },
    {
      prompt: {
        pl: "Co mierzy podobieństwo kosinusowe w prostym RAG?",
        en: "What does cosine similarity measure in a simple RAG?",
      },
      options: [
        {
          text: {
            pl: "Jak blisko siebie leżą dwa wektory, czyli jak zbliżone jest ich znaczenie",
            en: "How close two vectors are, that is how similar their meaning is",
          },
        },
        {
          text: {
            pl: "Liczbę wspólnych słów w dwóch dokumentach",
            en: "The number of shared words between two documents",
          },
        },
        {
          text: {
            pl: "Czas potrzebny na policzenie embeddingu",
            en: "The time needed to compute an embedding",
          },
        },
        {
          text: {
            pl: "Liczbę tokenów w zapytaniu użytkownika",
            en: "The number of tokens in the user's query",
          },
        },
      ],
      answer: 0,
      explanation: {
        pl: "Podobieństwo kosinusowe ocenia kąt między wektorami. Wartość bliska 1 oznacza zbliżone znaczenie, dlatego zwracamy fragmenty o najwyższym wyniku.",
        en: "Cosine similarity scores the angle between vectors. A value near 1 means similar meaning, so we return the chunks with the highest score.",
      },
    },
    {
      prompt: {
        pl: "Do czego służy TestEmbeddingModel?",
        en: "What is TestEmbeddingModel for?",
      },
      options: [
        {
          text: {
            pl: "Zwraca deterministyczne wektory bez wywołań API, do szybkich i powtarzalnych testów",
            en: "It returns deterministic vectors without API calls, for fast and repeatable tests",
          },
        },
        {
          text: {
            pl: "Trenuje nowy model embeddingów na Twoich danych",
            en: "It trains a new embedding model on your data",
          },
        },
        {
          text: {
            pl: "Automatycznie wybiera najlepszego dostawcę embeddingów",
            en: "It automatically picks the best embedding provider",
          },
        },
        {
          text: {
            pl: "Przyspiesza produkcyjne wywołania API do modelu",
            en: "It speeds up production API calls to the model",
          },
        },
      ],
      answer: 0,
      explanation: {
        pl: "TestEmbeddingModel podmieniasz przez embedder.override i dostajesz stałe wektory bez kosztu ani opóźnienia API, więc testy RAG są szybkie i deterministyczne.",
        en: "You swap TestEmbeddingModel in via embedder.override and get fixed vectors with no API cost or latency, so RAG tests stay fast and deterministic.",
      },
    },
  ],
};
